### ISSUE TITLE
Please bump a new version to npm

### ISSUE THREAD

**Issue by jiverson** [tschaub/gh-pages#114]
Wrench is now deprecated would be nice to see a new version up on npm.

**Comment by jvanaert** [comment]
any news on creating a new npm version pls ?

**Comment by tschaub** [comment]
Thanks for bumping this.  I just published `gh-pages@0.12.0` - see [the changelog](https://github.com/tschaub/gh-pages/blob/master/changelog.md#v0120) for what was included.

**Comment by jvanaert** [comment]
Thank you!
