### ISSUE TITLE
Anyway to deploy to master?

### ISSUE THREAD

**Issue by CrashyBang** [tschaub/gh-pages#117]
[#14](https://github.com/tschaub/gh-pages/issues/14) is related but I am not sure?

Wanting to deploy to `master` for a user repo which does not read from `gh-pages`.

Cheers.

**Comment by ehgoodenough** [comment]
You can use the `branch` option to set what branch you want to use:

https://github.com/tschaub/gh-pages#optionsbranch

**Comment by tschaub** [comment]
See @ehgoodenough answer if you are calling `publish()` yourself.  If you are using the CLI, the option is `--branch`.  E.g.
```
gh-pages --dist dist --branch master
```

The CLI needs documentation.
