### ISSUE TITLE
"Remote url mismatch" error refers to the "clean" Grunt task

### ISSUE THREAD

**Issue by markdalgleish** [tschaub/gh-pages#12]
If you encounter the "Remote url mismatch" error, the instructions for correcting the issue are still Grunt-specific:

"Remote url mismatch.  Got "X" but expected "Y" in node_modules/gh-pages/.cache.  If you have changed your "repo" option, try running the "clean" task first."

**Comment by dkebler** [comment]
Getting this error, but not using gh-pages from the CL.

I see there is a .clean method exported in index.js,  can you document use of that programatically in the readme?

**Comment by jaywcjlove** [comment]
Delete Repository, re clone.

**Comment by barancezayirli** [comment]
Don't need to delete and reclone the repo. You can uninstall and install the gh-pages again with npm.

**Comment by dsernst** [comment]
I've run into this problem a few times, and kept forgetting the solution. Adding this script to my `package.json` replaced the missing `clean` task it refers to:

```
"scripts": {
    "clean": "rm -rf node_modules/gh-pages/.cache",
}
```

**Comment by tschaub** [comment]
The changes in #173 make it so this problem shouldn't come up again.  It also adds a `gh-pages-clean` script for people that want to manually delete the cached clones.
