### ISSUE TITLE
gh-page npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

### ISSUE THREAD

**Issue by alexeikaratai** [tschaub/gh-pages#133]
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

─┬ gh-pages@0.11.0
  └── wrench@1.5.8

**Comment by felquis** [comment]
@alexeikaratai can you send a PR fixing it?

**Comment by ehgoodenough** [comment]
If I understand correctly, this problem was resolved by switching from wrench to rimraf, as addressed by #78. As discussed in #114, we need to bump the version of npm to fix this.

**Comment by tschaub** [comment]
See `gh-pages@0.12.0`.
