### ISSUE TITLE
Use an alternative to q-io/fs

### ISSUE THREAD

**Issue by dignifiedquire** [tschaub/gh-pages#152]
I've been using this module with great enjoyment, but sadly it breaks other code by simply requiring it. You can find the details here: https://github.com/dignifiedquire/aegir/issues/79#issuecomment-265995866. The gist is, that `q-io` uses a module `collections` which modifies global prototypes.

This could be easily fixed here, by using something another promise wrapper around `fs` than `q-io`. I've also opened an issue on `q-io` to fix this, but wanted to mention this here as well. https://github.com/kriskowal/q-io/issues/160

**Comment by le-idiot** [comment]
There's already an issue #42 and an abandoned PR #44

**Comment by dignifiedquire** [comment]
Sorry about that, didn't see it. Closing as duplicate
