### ISSUE TITLE
Unable to run clean task

### ISSUE THREAD

**Issue by just-boris** [tschaub/gh-pages#156]
When I have made some changes in the configuration, the tool said me the following

```
Remote url mismatch.  Got "<something>" but expected "<something-else>" in node_modules/gh-pages/.cache. 
If you have changed your "repo" option, try running the "clean" task first.
```

I have tried to run `gh-pages clean`, but it didn't succeed. What kind of task should I run to clean the cache?

**Comment by kevincolten** [comment]
you can run `rm -rf node_modules/gh-pages/.cache` to clean the cache manually

**Comment by just-boris** [comment]
Actually, there is [a `clean` function](https://github.com/tschaub/gh-pages/blob/master/lib/index.js#L243) exported from the code.

I wanted to do the same operation via CLI. If it is not possible now, I will be happy to send a PR. How about command?

```
gh-pages --clean
```

**Comment by paulcpederson** [comment]
@just-boris that function is in the lib, not in the cli.

@tschaub this tripped me up just now as well, but @kevincolten 's solution works well. I think it might be enough to just change the error message to:

```
Remote url mismatch.  Got "<something>" but expected "<something-else>" in node_modules/gh-pages/.cache. 
If you have changed your "repo" option, try clearing the cache by running:
  rm -rf node_modules/gh-pages/.cache
```

Let me know if you want me to open a pr with that change.

**Comment by newswim** [comment]
Since I was using `nvm` I had to run

    rm -rf ~/.nvm/versions/node/v7.6.0/lib/node_modules/gh-pages/.cache

**Comment by tschaub** [comment]
With the changes in #173, these cache collisions shouldn't be a problem any more.  In addition, the package will now make a `gh-pages-clean` script available so people can remove all cached clones.
