### ISSUE TITLE
Allow .cache directory to be configurable?

### ISSUE THREAD

**Issue by bebraw** [tschaub/gh-pages#16]
It looks like `gh-pages` figures out `.cache` dir like this:

``` javascript
function getCacheDir() {
  return path.relative(process.cwd(), path.resolve(__dirname, '../.cache'));
}
```

This can get rather nasty in case you are using `gh-pages` in a cli wrapper. What if we introduced `cachePath` option that, if set, would override this function? This would give me the flexibility I need.

**Comment by regular** [comment]
Isn't the `clone` option doing what you are looking for?

**Comment by bebraw** [comment]
@regular That's actually close! I realized there's a little issue, though. `copy(files, basePath, options.clone);` will fail if `clone` directory is within `basePath`. You would need to do something more clever than that for this to work. As it is, it will yield just `ENOENT, mkdir ''`.

**Comment by regular** [comment]
@bebraw I got that too (also have the clone directory inside the basePath). I was able to resolve this by using relative paths rather than absolute paths. There seems to be a bug in utils.js that only surfaces when paths are absolute.

**Comment by bebraw** [comment]
@regular Ah, I see. Thanks for the tip!
