### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by brentertz** [tschaub/gh-pages#164]
I am considering using this package in a project of mine, but I am concerned about the high number of issues and pull requests that don't seem to be getting that much attention from the maintainers.  I understand that it is open-source and that people get busy with other things and that is fine.  I am just honestly curious as to whether this project still maintained.  Thanks!

**Comment by tschaub** [comment]
My intention has been to rework the implementation so it is better tested and ideally offers simpler configuration.

I have been avoiding merging pull requests that don't go in that direction (better tested and simpler config).  It is fair to ask whether the project is being actively maintained.  I'd say at this point, the attitude is "if it ain't broke...".  There are open pull requests that propose breaking changes (#162 makes it so the current `--depth` arg is ignored, #161 provides new functionality without any tests (a fault of the original setup, not the PR author), etc.)

Hope that gives you a sense of the state of the project.  In short, contributions that make the project easier to maintain would be very welcome (and contributions that look like potential liabilities are not getting attention).

**Comment by brentertz** [comment]
Thank you kindly for your clear explanation.
