### ISSUE TITLE
Removing remote gh-pages branch causes crash (with workaround)

### ISSUE THREAD

**Issue by harlantwood** [tschaub/gh-pages#17]
I love this module, thanks : )

I decided to blow away my gh-pages branch from github, and start fresh.  When I did this, and re-ran [my script](https://github.com/enlightenedstructure/enlightened-structures/blob/2554c9e92270d325cc1173342f25ffcd53664608/bin/publish), I got the following error:

```
Cloning git@github.com:.../....git into node_modules/gh-pages/.cache
Cleaning
Fetching origin
{ [ProcessError: fatal: Couldn't find remote ref refs/heads/gh-pages]
  code: 128,
  message: 'fatal: Couldn\'t find remote ref refs/heads/gh-pages\n',
  name: 'ProcessError' }
```

I fixed this by simply reinstalling the package:

```
rm -rf node_modules/gh-pages/ && npm install
```

And all worked fine.  Just wanted to report the issue in case it is helpful, or in case it helps others who may be searching for a fix.

**Comment by harlantwood** [comment]
This is still an issue in the latest version btw.  But here is an even simpler workaround, which I now run every time before doing the gh-pages magic:

`rm -rf node_modules/gh-pages/.cache`

**Comment by Ding-Fan** [comment]
Same issue!
Thank you for solution 😁

**Comment by tschaub** [comment]
After the changes in #173 are published, you'll be able to run `gh-pages-clean` to recover from this situation.  Any contributions to improve the docs would be appreciated.

**Comment by itsmichaeldiego** [comment]
Thanks for the change and for the amazing library, @tschaub! `npm run gh-pages-clean` worked like a charm.

**Comment by llevvi** [comment]
Thanks a lot for sharing! I haven't spent more than a minute researching!

**Comment by whhsu2** [comment]
Same issue ! Thanks for sharing

**Comment by chaos-sl** [comment]
npx gh-pages-clean
or
./node_modules/.bin/gh-pages-clean

**Comment by minkukjo** [comment]
Thanks a lot!

**Comment by yuvan11** [comment]
*This is how I resolved it*

- I had my deploy script
   
            "deploy": "gh-pages -d build"
- I changed it to 

           "deploy": "gh-pages-clean gh-pages -d build"

-  Then execute,
         
           npm run deploy

- I changed my deploy script to the previous state 
     
            "deploy": "gh-pages -d build"

- Now, 
          
             npm run deploy
