### ISSUE TITLE
unable to prevent removal of CNAME

### ISSUE THREAD

**Issue by travi** [tschaub/gh-pages#179]
I ran across [your suggestion](https://github.com/tschaub/gh-pages/pull/75) to use `--remove` with negation to prevent removal of specific files when using the cli, but have been unable to get that working. 

Is that approach still supported/recommended?

**Comment by stephenmathieson** [comment]
Any news here?

**Comment by emschwartz** [comment]
I needed to prevent it from removing a `.nojekyll` file and made that work by using the config option: `src: ["**/*", ".nojekyll"]`

**Comment by fang0rnz** [comment]
Same here, it isn't working.

**Comment by fang0rnz** [comment]
I'm not sure why but "-a" seems to fix the issue.

"deploy": "gh-pages -d build -a"

**Comment by siakaramalegos** [comment]
FYI, `-t` or `--dotfiles` keeps dotfiles. `-a` does "Only add, and never remove existing files". You can find all the options by running `gh-pages --help`. Glad someone else had this problem because it gave me a clue to look there.

**Comment by travi** [comment]
for those finding this thread, it is worth being aware that `-a` does prevent removal of the `CNAME` file, but it also prevents removal of _every_ other file as well, which is a big deal when you have to version a bunch of generated files that vary over time since github pages doesnt support a build step at deploy time.

as nice as github pages is for simple things, those two issues have motivated me to move most of my static sites to netlify instead.
