### ISSUE TITLE
Failed to get remote.origin.url (task must either be run in a git repository with a configured origin remote or must be configured with the "repo" option)

### ISSUE THREAD

**Issue by scottkimGit** [tschaub/gh-pages#192]
Hello,

Just following the deployment guide from https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

- The budget-planner app I'm building hasn't got any changes in it. It's a default app created by create-react-app. 
- My SSH key to GitHub is working good.
- The test repository I'm trying to deploy also has set up with another deployment key that has been loaded to my ssh-agent with write access.
- Node(6.11.1) and NPM(3.10.10) has been upgraded to the latest today.
- When I run 'npm run deploy', I get the following error

_> budget-planner@0.1.0 deploy /Users/scott/Developer/personal/budget-planner
> gh-pages -d build

Failed to get remote.origin.url (task must either be run in a git repository with a configured origin remote or must be configured with the "repo" option)._

Also, npm-debug.log file has:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy',
1 verbose cli   '--verbose' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle budget-planner@0.1.0~predeploy: budget-planner@0.1.0
6 verbose lifecycle budget-planner@0.1.0~predeploy: unsafe-perm in lifecycle true
7 verbose lifecycle budget-planner@0.1.0~predeploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/scott/Developer/personal/budget-planner/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/Users/scott/bin/google_appengine:/usr/local/go/bin/:/Users/scott/Developer/go/bin:/Users/scott/Developer/android-sdk-macosx/tools:/Users/scott/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
8 verbose lifecycle budget-planner@0.1.0~predeploy: CWD: /Users/scott/Developer/personal/budget-planner
9 silly lifecycle budget-planner@0.1.0~predeploy: Args: [ '-c', 'npm run build' ]
10 silly lifecycle budget-planner@0.1.0~predeploy: Returned: code: 0  signal: null
11 info lifecycle budget-planner@0.1.0~deploy: budget-planner@0.1.0
12 verbose lifecycle budget-planner@0.1.0~deploy: unsafe-perm in lifecycle true
13 verbose lifecycle budget-planner@0.1.0~deploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/scott/Developer/personal/budget-planner/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/Users/scott/bin/google_appengine:/usr/local/go/bin/:/Users/scott/Developer/go/bin:/Users/scott/Developer/android-sdk-macosx/tools:/Users/scott/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
14 verbose lifecycle budget-planner@0.1.0~deploy: CWD: /Users/scott/Developer/personal/budget-planner
15 silly lifecycle budget-planner@0.1.0~deploy: Args: [ '-c', 'gh-pages -d build' ]
16 silly lifecycle budget-planner@0.1.0~deploy: Returned: code: 1  signal: null
17 info lifecycle budget-planner@0.1.0~deploy: Failed to exec deploy script
18 verbose stack Error: budget-planner@0.1.0 deploy: `gh-pages -d build`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:891:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid budget-planner@0.1.0
20 verbose cwd /Users/scott/Developer/personal/budget-planner
21 error Darwin 16.6.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy" "--verbose"
23 error node v6.11.1
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error budget-planner@0.1.0 deploy: `gh-pages -d build`
26 error Exit status 1
27 error Failed at the budget-planner@0.1.0 deploy script 'gh-pages -d build'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the budget-planner package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     gh-pages -d build
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs budget-planner
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls budget-planner
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

Any help please?

**Comment by vectorzeng** [comment]
me too

**Comment by vectorzeng** [comment]
you should add remote url for your project , then run gh-pages -d build.

**Comment by carpben** [comment]
I get the same error. 
I followed the instructions on https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages 
I have added  "homepage": "https://carpben.github.io/fccLeaders/" to my package.json. And I have remote set on my git (When I do push it logs "everything up to date". 

The terminal I'm using is bash on ubuntu on Windows. And it might be the issue. I used bash for this project till now. However, when I try moving to PowerShell and give the command npm run build it says it doesn't recognise react-script. I guess it is because create-react-app installed the bash version not the windows version. 
Any diagnosis or possible solutions?

**Comment by jonnyrude** [comment]
I just had the same issue and was able to resolve it. Here's what I did:

In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github. 

My other remote pointed to the same url, it just wasn't called 'origin'. 

Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

**Comment by TomerShech** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Thank you so much you saved me

**Comment by sboots** [comment]
The troubleshooting steps at <https://github.com/facebook/create-react-app/issues/3216> are really helpful for this error message.

For Mac users, one potential cause of this issue is upgrading to Mojave (which silently uninstalls the command line version of git). In that case, you can reinstall the Xcode command line tools (which include git) by running `xcode-select --install`. More details on this are here: <https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path>

**Comment by EdixonAlberto** [comment]
In my case the problem was solved by renaming my remote control by * 'origin' * 👍😁

**Comment by Asjidkalam** [comment]
> In my case the problem was solved by renaming my remote control by **'origin'**

same!

**Comment by vrathnayake** [comment]
@jonnyrude thanks. That's what was missing

**Comment by GokulRG** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Bruh!! This is still helping people to this day!!!!!

**Comment by bhanupsingh77** [comment]
@jonnyrude thanks

**Comment by Nanotekfr** [comment]
@jonnyrude thanks 👍

**Comment by fpeniche** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

it helped me today, thanks

**Comment by Klowar** [comment]
If u won't to add origin repo, just change command
`
"deploy": "gh-pages -d build"
`
to 
`
"deploy": "gh-pages -d build -r <repo_url>"
`

Also to check all available flags just run `npx gh-pages --help`

**Comment by ageprocpp** [comment]
Now, I would like to use two remotes, one is to push the source itself, and the other is to push the built files.
When I want to push to the remote whose name is not 'origin', should I use option '-r' and specify URL?
I added the remote with an other name and tried to use '-o' option, but failed.

**Comment by CaiYiLiang** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

This work for me!

**Comment by omarbassam88** [comment]
> > I just had the same issue and was able to resolve it. Here's what I did:
> > In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> > My other remote pointed to the same url, it just wasn't called 'origin'.
> > Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.
> 
> Bruh!! This is still helping people to this day!!!!!

Thanks This was really Clear and Helpful

**Comment by AzriRahmat-SDev** [comment]
> If u won't to add origin repo, just change command
> `"deploy": "gh-pages -d build"`
> to
> `"deploy": "gh-pages -d build -r <repo_url>"`
> 
> Also to check all available flags just run `npx gh-pages --help`

thank this helped me a lot

**Comment by suyash-patil** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Thanks a lot.

**Comment by milesfrain** [comment]
I was having this same issue on an older version of gh-pages, but it is **now fixed after updating to version 3.1.0**. See https://github.com/tschaub/gh-pages/issues/290#issuecomment-667608954

**Comment by 11611746** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

This really worked for me

**Comment by clintonhays** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Almost exactly 2 years later and your post has saved this React newb. Thanks!

**Comment by EduardoVasquez9** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Best solution so far!

**Comment by PrincessBeni** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

You just saved me. However, only my html files got deployed. All the pages I
 created by myself have not been deployed.

**Comment by ehrenChenEJ** [comment]
> If u won't to add origin repo, just change command
> `"deploy": "gh-pages -d build"`
> to
> `"deploy": "gh-pages -d build -r <repo_url>"`
> 
> Also to check all available flags just run `npx gh-pages --help`

Thanks it helps me a lot!

**Comment by Code2Rithik** [comment]
> If u won't to add origin repo, just change command
"deploy": "gh-pages -d build"
to
"deploy": "gh-pages -d build -r <repo_url>"

Also to check all available flags just run npx gh-pages --help

This worked for me today

**Comment by RensGits** [comment]
> If u won't to add origin repo, just change command
> `"deploy": "gh-pages -d build"`
> to
> `"deploy": "gh-pages -d build -r <repo_url>"`
> 
> Also to check all available flags just run `npx gh-pages --help`

Worked for me too!

**Comment by AnastasiosPas** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Yeeeeees, thanks a lot!!!!!!!

**Comment by Spacefox123** [comment]
> 
> 
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Worked for me too. Thanks!

**Comment by AnastasiosPas** [comment]
Hey, thank you so much taking the time to reply to me. Indeed, I have solved it by now but it is great to read your way. It is exactly what worked for me too actually! I searched a lot around for that haha. I wish I had your reply earlier! Thanks again, all the best!

**Comment by chrahman** [comment]
If u won't to add origin repo, just change command
"deploy": "gh-pages -d build"
to
"deploy": "gh-pages -d build -r <repo_url>"

Also to check all available flags just run npx gh-pages --help

Worked for me too!

**Comment by Awokoya** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

This really helped. Thanks

**Comment by gjaynir0508** [comment]
> If u won't to add origin repo, just change command
> `"deploy": "gh-pages -d build"`
> to
> `"deploy": "gh-pages -d build -r <repo_url>"`
> 
> Also to check all available flags just run `npx gh-pages --help`

Thank you very much. This is really helpful even when you don't want to rename your remote to origin.

**Comment by AlexWebDev01** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

Thank you so much! It works!)

**Comment by mrmalik16** [comment]
> > I just had the same issue and was able to resolve it. Here's what I did:
> > In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> > My other remote pointed to the same url, it just wasn't called 'origin'.
> > Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.
> 
> Thank you so much! It works!)

I'm doing this for the first time in VS Code's terminal and don't find the answer useful there. Can you tell me how can I use the "npm run deploy" command successfully inside VS Code's terminal? Thanks!

**Comment by Rickyoung221** [comment]
In my case, It says 'The build folder is ready to be deployed.'
However, I didn't see there is a new branch. 
Does anyone know why?  Thx in advance

**Comment by kiruushinde** [comment]
Yaar really i don't have words to say special thanks to you guys...😍😍
i was also having the same issue, but now feeling like -> 😁😎
Thanks a lot 💕

**Comment by harish343** [comment]
You are like coming from heaven Thank all of you guys my problem is solved
problem =>failed to get remote.origin.url
solution => git remote add origin <url> then npm run deploy

**Comment by nvavinash** [comment]
thanks a lot bruh...

**Comment by amanwild** [comment]
>

**Comment by traynhamdavid426** [comment]
0

I had the same issue. I solved it by putting the following commands in the terminal: git init, git remote add origin (copy and paste the url from your github repository here, the parentheses are not needed), and then npm run deploy

**Comment by mubashir-mehran** [comment]
I just had the same issue and was able to resolve it. Here's what I did:

In my terminal, when I ran git remote -v, I did not see any remote's withe the name 'origin'. So, I added one with git remote add origin <url>, with the URL of my repository on Github.

My other remote pointed to the same url, it just wasn't called 'origin'.

Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

**Comment by SamNijin** [comment]
I renamed the remote name as origin and then my problem get solved.

**Comment by Attar92** [comment]
Here's the same problem...
Any help please...

**Comment by Attar92** [comment]
> I renamed the remote name as origin and then my problem get solved.

What does that mean?

**Comment by rodrigoangeli** [comment]
I was able to fix this, I'm working on Windows and for some reason my subdirectories didn't have the same ownership/permission as root, like node_modules didn't have the same ownership as root, so I changed that and the command worked.

**Comment by FranelTOVIDJALE** [comment]
> > I just had the same issue and was able to resolve it. Here's what I did:
> > In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> > My other remote pointed to the same url, it just wasn't called 'origin'.
> > Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.
> 
> Thank you so much you saved me

You saved me too . Thank's

**Comment by pratikbanger** [comment]
> I just had the same issue and was able to resolve it. Here's what I did:
> 
> In my terminal, when I ran `git remote -v`, I did not see any remote's withe the _name_ 'origin'. So, I added one with `git remote add origin <url>`, with the URL of my repository on Github.
> 
> My other remote pointed to the same url, it just wasn't called 'origin'.
> 
> Then, when I ran 'npm run deploy' everything worked. I hope this helps, though it's a year after you last posting.

This really worked thanks bro!!

**Comment by ArtYu12** [comment]
> Если вы не хотите добавлять исходное репо, просто измените команду `"deploy": "gh-pages -d build"` на `"deploy": "gh-pages -d build -r <repo_url>"`
> 
> Также, чтобы проверить все доступные флаги, просто запустите`npx gh-pages --help`


Thank you very much!It works now

**Comment by dhanur350** [comment]
I have the same issue I have remote name origin and still getting this error, 
Failed to get remote.origin.url (task must either be run in a git repository with a configured origin remote or must be configured with the "repo" option).

Here is my package.json file
{
  "name": "testapp",
  "version": "0.1.0",
  "homepage": "https://dhanur350.github.io/testapp",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "gh-pages": "^5.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "predeploy":"npm run build",
    "deploy": "gh-pages -d build",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
 

Any suggestions to fix this....??

**Comment by grumd** [comment]
My origin was set up correctly, but because the repository folder was copied from another machine, deploying didn't work.
I deleted the repository and cloned it again, and the issue was fixed.

**Comment by dhanur350** [comment]
> My origin was set up correctly, but because the repository folder was copied from another machine, deploying didn't work. I deleted the repository and cloned it again, and the issue was fixed.

Mine isn't working still the same issue

**Comment by zhouzhou0619** [comment]
> 

Thank you, this works for me. 
Really appreciate!

**Comment by ashiqans** [comment]
> I get the same error. I followed the instructions on https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages I have added "homepage": "https://carpben.github.io/fccLeaders/" to my package.json. And I have remote set on my git (When I do push it logs "everything up to date".
> 
> The terminal I'm using is bash on ubuntu on Windows. And it might be the issue. I used bash for this project till now. However, when I try moving to PowerShell and give the command npm run build it says it doesn't recognise react-script. I guess it is because create-react-app installed the bash version not the windows version. Any diagnosis or possible solutions?

after ages, you saved my day. thank you so much buddy! cheers!

**Comment by Phil-Libra** [comment]
Same problem. 

`remote add origin <url>` did not work for me cause there're already origin urls in `git remote -v`.

Finally I changed the owner of the folder and it solved.

**Comment by leassis91** [comment]
thats it, guys. if you've copied your folder from other machine or had factory reset your computer, you have to clone the repo again, then it will be solved :D

**Comment by Ayrlin-Renata** [comment]
I have solved this issue without re-cloning the folder.

I encountered the issue after moving a hard drive with my repo, essentially copying my folder to another machine.

if you do `git config --list`, everything will appear to be fine, it will list correct remote.origin.url.
however, if you do `git config --global --list`, the issue becomes apparent, as it is missing. 

**add your URL to global using `git config --global remote.origin.url [url]` and the issue will be solved.**

you may encounter ownership issues after this, which you can resolve by changing ownership of the folder in your OS and if necessary, deleting the .cache folder that is the issue (this will cause the entire gh-pages to be reuploaded).

**Comment by iddhi-sulakshana** [comment]
> Same problem.
> 
> `remote add origin <url>` did not work for me cause there're already origin urls in `git remote -v`.
> 
> Finally I changed the owner of the folder and it solved.

Thanks this works for me, I used my second disk and it root has the ownership of the directory after changing it to current user I was able to run it successfully :smile:

**Comment by ShinuRaju** [comment]
This worked for me finally 

{
  "name": "your-project",
  "version": "1.0.0",
  "scripts": {
    "predeploy": "npm run build",
    "deploy": "gh-pages-clean && gh-pages -d build"
  },
  "devDependencies": {
    "gh-pages": "^3.2.3"
  }
}


and then run npm run deploy

**Comment by imki123** [comment]
> This worked for me finally
> 
> "web-vitals": "^2.1.4" }, "scripts": { "start": "react-scripts start", "build": "react-scripts build", "test": "react-scripts test", "eject": "react-scripts eject", "predeploy": "npm run build", "deploy": "gh-pages-clean && gh-pages -d build -r https://github.com/ShinuRaju/shirt-color-changer.git" }, "devDependencies": { "gh-pages": "^6.1.1" }
> 
> also i changed the remote.origin.url git config --global remote.origin.url "https://github.com/ShinuRaju/shirt-color-changer.git"
> 
> and then run npm run deploy

`gh-pages-clean` works for me. Thank you!

**Comment by Normone** [comment]
I don't know why it stopped working. Yesterday everything was published perfectly, but today it stopped. Adding `gh-pages-clean` helped me too.
