### ISSUE TITLE
Alternative module name

### ISSUE THREAD

**Issue by alexlawrence** [tschaub/gh-pages#194]
First of all: I really like this module. It works just out of the box and provides a lot of useful configuration possibilities. Thanks for the great work!

Initially, I used gh-pages to deploy static files to a gh-pages branch. With that in place I also searched for a module to deploy dist files to a release branch and eventually create a tag. I tried various different packages/modules but none simply worked without any errors. Only then I discovered that this module is also capable of doing that. That is why I´m using it now also for deploying to the release branch.

Therefore, my question: Have you considered given this module a more intention revealing name?

**Comment by alexlawrence** [comment]
I´m using the module in a second project now for something completely else. Therefore again: What do you think giving this module a name that is more generic?

**Comment by tschaub** [comment]
I called it `gh-pages` originally because I thought that would help people find it.  But as you've found, it can be used for more than updating a `gh-pages` branch.  Any suggestions on a more generic name or a better description?  Rather than renaming, it could make sense to update the keywords or description to make it easier to find.

**Comment by alexlawrence** [comment]
In the end it´s not cruicial for the functionality what the name of the module is. :-) It´s just that I´m a big fan of intention revealing naming. I understand that renaming the module (including all the implications) may not be worth it.

Maybe it helps to think about the

**Comment by alexlawrence** [comment]
As far as understood, the module will not be renamed. Therefore this issue can be closed imo.
