### ISSUE TITLE
Custom domain gets deleted on deploy - CNAME not working

### ISSUE THREAD

**Issue by whoisryosuke** [tschaub/gh-pages#236]
I have an issue where each time I use gh-pages to deploy, my custom domain gets deleted. I tried adding a CNAME file to my project with the domain name, but it doesn't change anything. Each deploy I have to manually set the domain again.

I run `gh-pages -d public` when deploying.

You can see the project repo here:
[https://github.com/whoisryosuke/ryosuke-gatsby-blog](https://github.com/whoisryosuke/ryosuke-gatsby-blog)

Not sure if this is an issue with my stack (GatsbyJS) or the gh-pages lib.

**Comment by Ehesp** [comment]
Also getting this issue

**Comment by adamsandle** [comment]
In your instance add the CNAME file to the static folder.

**Comment by whoisryosuke** [comment]
@adamsandle the CNAME file is in the `gh-pages` branch when I deploy (https://github.com/whoisryosuke/ryosuke-gatsby-blog/blob/gh-pages/CNAME), but I'll add it to the static folder and see if it makes a difference 👍

**Comment by ivoilic** [comment]
I'm also having this issue. You have to manually re-enter the costume domain in the repos settings and in my case turn off force https.

**Comment by whoisryosuke** [comment]
@ivoilic I was able to resolve this by committing the CNAME file to the branch gg-pages deploys from.

**Comment by juniorpires** [comment]
Thanks. It helps a lot.

**Comment by kietnam** [comment]
I have the same issue..

**Comment by LeslieOA** [comment]
> @ivoilic I was able to resolve this by committing the CNAME file to the branch gg-pages deploys from.

Where and/or how should I be committing the CNAME to the repo?
I'm using [Gatsby with a public repository](https://github.com/LeslieOA/leslieoa.github.io/). 
Is this in the docs or am I missing something? Thanks.

**Comment by whoisryosuke** [comment]
@leslieoa should be something like (assuming you push to origin):

`git checkout gh-pages
git add CNAME
git commit -m ‘:wrench: Added CNAME’
git push gh-pages origin`

**Comment by LeslieOA** [comment]
x

> @LeslieOA should be something like (assuming you push to origin):
> 
> `git checkout gh-pages git add CNAME git commit -m ‘:wrench: Added CNAME’ git push gh-pages origin`

Hey Ryosuke.
Ah! So I need a (plaintext/`text/plain`?) file named `CNAME` in the root of my repository?
Any link(s) to the docs for it's format/content(s)?

Thanks.

_P.S. Nice (Gatsby) site BTW!_

**Comment by whoisryosuke** [comment]
@LeslieOA yep. plaintext with your domain in it. [you can see an example in my repo.](https://github.com/whoisryosuke/ryosuke-gatsby-blog/blob/gh-pages/CNAME)
 and thanks 😊

**Comment by jwld** [comment]
Still having this issue - do you have to commit the CNAME on the `gh-pages` branch every time you deploy?

**Comment by jwld** [comment]
Ah right, for anyone else having this issue just keep a `CNAME` record in the `dist` folder or whatever you're deploying from.

**Comment by giteshjha** [comment]
For angular 8. 
Create a CNAME file inside the src folder.
then Inside angular.json 
"assets": [
              "src/favicon.ico",
              "src/assets",
              "src/CNAME"    // This is the change you need to make.
            ],

**Comment by sanny-io** [comment]
For those who use `create-react-app`, put the CNAME file in the public folder and it will be part of the build output.

**Comment by colinmorris** [comment]
> In your instance add the CNAME file to the static folder.

Just to add some context to this excellent solution from adamsandle, [here's the documentation](https://www.gatsbyjs.org/docs/static-folder/) on the static folder. If it doesn't already exist, you'll need to create a directory called `static` at the root of your project.

**Comment by Abhay07** [comment]
I guess you have alreayd figured out the issue that, CNAM file is removed, if you deploy new changed. You need to take backup of the CNAME file and then put it after the build is made. I wrote a shell script for doing this in making this tool [MyIps](https://myips.in)

**Comment by Nirzak** [comment]
> > In your instance add the CNAME file to the static folder.
> 
> Just to add some context to this excellent solution from adamsandle, [here's the documentation](https://www.gatsbyjs.org/docs/static-folder/) on the static folder. If it doesn't already exist, you'll need to create a directory called `static` at the root of your project.

Thanks the static folder method is working like a charm. Everyone who is using automatic deploying script just put your CNAME file in a static folder. The script will include the CNAME file on the next deployment.

**Comment by davegallant** [comment]
For any [hugo](https://github.com/gohugoio/hugo)ers, this fixed it permanently for me:

```sh
echo 'mydomain.com' > static/CNAME
```

**Comment by davegallant** [comment]
For any [hugo](https://github.com/gohugoio/hugo)ers, this fixed it permanently for me:

```sh
# in the main branch
echo 'mydomain.com' > static/CNAME
```

**Comment by fedorovpishet** [comment]
@adamsandle thank you so much! You save me!!!

**Comment by cameronkruse** [comment]
> In your instance add the CNAME file to the static folder.

This is a pretty old thread, but where I found the answer to this question. One hang up I had was the CNAME file I downloaded as an example was converted to a `.txt` file when it was downloaded. The file that is added to the static folder should not have a filetype ending it should just be `CNAME` with the custom URL as it's contents.

**Comment by kaischreurs** [comment]
> One hang up I had was the CNAME file I downloaded as an example was converted to a `.txt` file when it was downloaded. The file that is added to the static folder should not have a filetype ending it should just be `CNAME` with the custom URL as it's contents.

Thank you so much, I've been trying to fix this for 15 minutes and this was the issue.

**Comment by AkAdmin68** [comment]
Use the cname argument.

`gh-pages -d dist --cname your-domain.com`
