### ISSUE TITLE
Vulnerability in dependence

### ISSUE THREAD

**Issue by ktquez** [tschaub/gh-pages#250]
I'm trying to install gh-pages and received from `npm audit` the message:
=== npm audit security report ===
Moderate:        Out-of-bounds Read
Package:         base64url
Patched in:      >=3.0.0
Dependency of:   gh-pages [dev]
Path:            gh-pages > base64url
More info:       https://nodesecurity.io/advisories/658

[!] 1 vulnerability found - Packages audited: 47 (47 dev, 0 optional)
Severity: 1 Moderate

**Comment by tschaub** [comment]
Thanks for the issue @ktquez.  I just published [`gh-pages@1.2.0`](https://github.com/tschaub/gh-pages/releases/tag/v1.2.0) with updated dependencies.  Now `npm audit` reports no vulnerabilities.

**Comment by ktquez** [comment]
Thanks @tschaub
And thanks also for gh-pages
