### ISSUE TITLE
2.0.0 deploy broken with Create-react-app

### ISSUE THREAD

**Issue by Diego-Fu** [tschaub/gh-pages#267]
I got the next error

```
> gh-pages -d build

Cannot read property 'email' of null
```

I downgraded to 1.2.0 now is working fine, not sure if work for other but with CRA is not working

**Comment by tschaub** [comment]
@Diego-Fu what do you you get when running the following (in the same directory where you run `gh-pages`?
```
git config user.name
git config user.email
```
