### ISSUE TITLE
Create an action for GitHub-Actions

### ISSUE THREAD

**Issue by ayush987goyal** [tschaub/gh-pages#276]
It would be great if we have an action that deploys to gh-pages. This cannot be done right now because github-actions runs in a container and gh-pages might not work in a container since the git config would not be set.

**Comment by nchaulet** [comment]
@ayush987goyal I just created a github action to deploy using this module 
https://github.com/nchaulet/github-action-gh-pages

I hope it can help you, and let me know if you have improvement ideas.

**Comment by tschaub** [comment]
Let me know if there is a change that could be made to this repo to make it easier for people to use as an action.

**Comment by nchaulet** [comment]
@tschaub it was pretty easy to use your module for a Github action. 👍
