### ISSUE TITLE
Build files not found net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by chrisdel101** [tschaub/gh-pages#285]
Probably this is common. I get 404 to all my build files.

Gh-pages will not find my files from `create-react-app` inside the build folder. I've tried moving them out, which has worked before. I manually renamed them this time but still not being found. 

Actual place:
`https://github.com/chrisdel101/baseballhack/blob/gh-pages/static/css/main.56da8e78.chunk.css`
Where gh-page is looking:
`https://chrisdel101.github.io/static/css/main.56da8e78.chunk.css `

Spent  a few hours on this now including following all the orthodox steps in CRA deployment tutorials.

**Comment by chrisdel101** [comment]
Not resolved but might as well close.

**Comment by JuanIrache** [comment]
Hi Chris,

Did you find a solution?

**Comment by chrisdel101** [comment]
I didn't. I wasn't able to use GH pages and instead made a server and used Heroku for that project.
Every time I use GH pages with create-react-app, which is common, it's a crapshoot whether I will be able to deploy it or not. Sometimes it works and sometimes it doesn't. I haven't figured out why yet so I can't reproduce the error.

**Comment by JuanIrache** [comment]
True. I kept trying and tweaking things here and there... and at some point it worked. Not sure what did it, really. I think GitHub struggles to clear previous versions of the site, so that makes debugging more difficult.

Thanks, though

**Comment by OnrHng** [comment]
hi there,, anyone find a solution?

best

**Comment by meta-meta** [comment]
Some helpful information here:
https://medium.com/swlh/building-a-static-single-page-application-with-javascript-for-github-pages-and-more-eb568b436bea#8f76

also here https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48

**Comment by jtremback** [comment]
@meta-meta FYI Medium link is paywalled

**Comment by jtremback** [comment]
You need to set the "homepage" key in package.json. For example:

“homepage” : “http://yourgithubname.github.io/yourreponame",

**Comment by Mahmoudhoko** [comment]
I've the same problem .. any one find a solution ?

**Comment by Mahmoudhoko** [comment]
> @meta-meta FYI Medium link is paywalled
it not working

**Comment by AlexanderKohr** [comment]
> You need to set the "homepage" key in package.json. For example:
> 
> “homepage” : “http://yourgithubname.github.io/yourreponame",

you safed my life. thank you so much!

**Comment by shieldgenerator7** [comment]
For me, the problem was that it wasn't properly navigating the folder structure. 
not working version:
`
    <script type="module" crossorigin src="/assets/index-43cca805.js"></script>
    <link rel="stylesheet" href="/assets/index-7a3c4c5b.css">`

working version:
`
    <script type="module" crossorigin src="./assets/index-43cca805.js"></script>
    <link rel="stylesheet" href="./assets/index-7a3c4c5b.css">`

Add a "." before the "/assets/...." part and the error will go away

I had to manually do this. I don't know how to get react to build it correctly

**Comment by HusakYurii** [comment]
> For me, the problem was that it wasn't properly navigating the folder structure. not working version:
> 
> ```
>     <script type="module" crossorigin src="/assets/index-43cca805.js"></script>
>     <link rel="stylesheet" href="/assets/index-7a3c4c5b.css">
> ```
> 
> working version:
> 
> ```
>     <script type="module" crossorigin src="./assets/index-43cca805.js"></script>
>     <link rel="stylesheet" href="./assets/index-7a3c4c5b.css">
> ```
> 
> Add a "." before the "/assets/...." part and the error will go away
> 
> I had to manually do this. I don't know how to get react to build it correctly

That worked for me! Thanks a lot!

It seems that when the `create-react-app` template makes a build it doesn't add "." to relative paths, which is becomes to be annoying when deploying to gh-pages

**Comment by Efess86** [comment]
Hey guys.
Like all of you I also encountered a problem with the paths to the script and styles files.
After all my nerves were exhausted and I entered a state of "I don't care anymore" I started wondering in which folder my scripts and styles are located?
You should know that I started to write a small application in vue3 + vite. I watched the video guide which is very easy to set up but the project was just created. 
So I started handwriting the paths in my browser and found that both scripts and styles were available. Here's an example.

("vue-invoices" is the name of my project)

the styles are displayed on this path
--> https://efess86.github.io/vue-invoices/assets/index-b3d70005.css

The path in the index.html of the dist folder after the npm run build command
--> <link rel="stylesheet" href="/vue-invoices/assets/index-b3d70005.css"> 

It seems to me that the problem is not that we write something wrong but that gitHub doesn't want to display what we give it for some reason.
I decided to check something and purposely wrote a non-existent path.

So here are my paths after I created the project with the command npm run build
<script type="module" crossorigin src="/vue-invoices/assets/index-1037ce7e.js"></script>
  <link rel="stylesheet" href="/vue-invoices/assets/index-b3d70005.css">

I specifically change the path in the stylesheet to href="/vue-invoices/non-exist-folder/index-b3d70005.css"

I write commit, wait 2 minutes and go to the project site to see what is written in the head tag. 

--> <link rel="stylesheet" href="/assets/index-b3d70005.css">

My updates didn't go through. Why? I probably got a ban because I updated the paths many times.

**Comment by Efess86** [comment]
I got email from gitHub

pages build and deployment: Some jobs were not successful

**Comment by Efess86** [comment]
I just discovered the Actions tab.
After you do anything on gitHub, open the Actions tab and see what happens there.

**Comment by Efess86** [comment]
So my story comes to an end.
I blame myself since I am a beginner.
I have 2 branches in my repository. 
Master and gh-pages. All the changes I made were in the master branch. These changes should have been done in the gh-pages branch.

Do not repeat my mistake and be careful. 
Everything is working fine for me. Vite put the right paths in on its own. I didn't use Vue router.
Sorry for writing so much.

**Comment by romanshutsman** [comment]
<base href="./">

**Comment by AlejoDevLov** [comment]
I had this issue with my React project. My solution was as follows:

I realized that I needed to modify the package.json file by adding the 'homepage' key, and the value should be the URL generated for GitHub. 
For example:
```
{
  ...
  "type": "module",
  "homepage": "https://alejodevlov.github.io/your-app-name", 
```


2. I found that I needed to modify the .css and .js paths in the index.html file generated after compiling the app for production. I had to add a dot at the beginning of the paths. 
For example:
```
<script type="module" crossorigin src="./assets/index-9503b887.js"></script>
<link rel="stylesheet" href="./assets/index-5c6ce281.css">
```

**Comment by AndreMicael** [comment]
> For me, the problem was that it wasn't properly navigating the folder structure. not working version:
> 
> ```
>     <script type="module" crossorigin src="/assets/index-43cca805.js"></script>
>     <link rel="stylesheet" href="/assets/index-7a3c4c5b.css">
> ```
> 
> working version:
> 
> ```
>     <script type="module" crossorigin src="./assets/index-43cca805.js"></script>
>     <link rel="stylesheet" href="./assets/index-7a3c4c5b.css">
> ```
> 
> Add a "." before the "/assets/...." part and the error will go away
> 
> I had to manually do this. I don't know how to get react to build it correctly


This worked perfectly for me. But I have do edit manually the index.html file on gh pages branch.

Thank you

**Comment by evgeniy-kolmak** [comment]
> You need to set the "homepage" key in package.json. For example:
> 
> “homepage” : “http://yourgithubname.github.io/yourreponame",

If you use **react-router-dom**, the root of the application is always `/`, but when expanding it tries to open `/your_project_name` and an error occurs in the routes.

**Comment by elhamhashemii** [comment]
> I had this issue with my React project. My solution was as follows:
> 
> I realized that I needed to modify the package.json file by adding the 'homepage' key, and the value should be the URL generated for GitHub. For example:
> 
> ```
> {
>   ...
>   "type": "module",
>   "homepage": "https://alejodevlov.github.io/your-app-name", 
> ```
> 
> 2. I found that I needed to modify the .css and .js paths in the index.html file generated after compiling the app for production. I had to add a dot at the beginning of the paths.
>    For example:
> 
> ```
> <script type="module" crossorigin src="./assets/index-9503b887.js"></script>
> <link rel="stylesheet" href="./assets/index-5c6ce281.css">
> ```

Hey. I have the same issue and did the same as you mentioned. I added a dot before /assets in the html file in my dist folder.
But when I run ```npm run deply``` it again removes those dots automatically. Have you faced this issue?

**Comment by lucy-c1** [comment]
> Hey. I have the same issue and did the same as you mentioned. I added a dot before /assets in the html file in my dist folder. But when I run `npm run deploy` it again removes those dots automatically. Have you faced this issue?

I had the same issue as well. I fixed this by switching my main branch to gh-pages on github and then directly, on github, modified my index.html file to be the correct file path. My project was already deployed then and it properly updated the page after a few minutes.
1. Make sure that you are on the correct branch. The main branch should be the default.
![image](https://github.com/user-attachments/assets/7a7ddc8f-08cc-4fc3-811f-e506c91fccd5)

2. Update the index.html file and commit your changes
![image](https://github.com/user-attachments/assets/80f7fbb3-c282-400b-b5f7-7622013a0716)

**Comment by peerdanish** [comment]
If you're using vite, then in **vite.config.ts**, add **base : './'** property. That solved the issue in my case.

**Comment by mickeymaruf** [comment]
I had the same issue with vite(react)
Adding "homepage" didn't solve it.

In vite.config.js you gotta set base to '/<REPO>/'
here's the source: https://vite.dev/guide/static-deploy

**Comment by mickeymaruf** [comment]
I had the same issue with vite(react)
Adding "homepage" didn't solve it.

In vite.config.js you gotta set base to "/your-repo/"
here's the source: https://vite.dev/guide/static-deploy
