### ISSUE TITLE
Allow an array of files to be passed through `src`

### ISSUE THREAD

**Issue by bebraw** [tschaub/gh-pages#29]
I had some troubles getting `glob` work the way I wanted today. It gets a little complicated in certain cases (multiple files/directories to match). It might be neat if `src` could accept an array of filenames. This way you could use whatever library you want on the user side. `glob` is a good default. I feel this would be a nice extension point, though, as it's just a single check on your side.

**Comment by chen844033231** [comment]
i have the same demand.
For example, such as the root directory, there is a readme.md and build directory of things also need to publish in the gh-pages branch. You need to manually write copy functions, take the readme.md copy to the build directory, and then in the gh-pages branch.

**Comment by mesupp** [comment]
jeah sorry i was instaling a debian on another pc and a mate said oh let me show... and when i came back i had another chore... Also thanx for the advice.... good thing i cleared my other hard diks too scratch and again sorry

**Comment by wayne5540** [comment]
This feature will be very useful. +1
