### ISSUE TITLE
The "file" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by konsumer** [tschaub/gh-pages#308]
I have a directory `dist/`, when I run `gh-pages --dist dist` from my package.json, I get this error:

`The "file" argument must be of type string. Received type undefined`

```
node: v12.7.0
Ubuntu (Pop!_OS 19.04)
```

**Comment by theycallmeswift** [comment]
I'm also receiving this error. 

```
node: 10.16.1
OSX 10.13.6
```

**Comment by sureshsevarthi** [comment]
Even I'm facing this error.

**Comment by bakerTX** [comment]
I am trying to deploy a fresh create-react-app to GitHub pages and I am getting this error now too.

```
node: 8.16.0
osx: 10.14.5
```

**Comment by jamsea** [comment]
I think this might be an issue of one of gh-pages's dependencies. I did a mass search in the codebase for the word "file" and don't see anything that would be emitting that that error. 

I also erased my yarn.lock file and regenerated it around 2 hours ago which is causing me to believe it's related to a subdependency

**Comment by hynra** [comment]
I got this error too.

**Comment by jamsea** [comment]
Another hint, when I run:
```
NODE_DEBUG=gh-pages yarn deploy
```
I see this:
```
$ gh-pages --dist=build
GH-PAGES 91884: Cloning https://github.com/jamsea/react-swapi.git into node_modules/gh-pages/.cache/github.com!jamsea!react-swapi.git
The "file" argument must be of type string. Received type undefined
error Command failed with exit code 1.
```

But when I try opening up the node_modules folder nothing was cloned, maybe git related?

**Comment by lopopolo** [comment]
The newly introduced `--git` argument seems to have no default value.

**Comment by lopopolo** [comment]
Adding `--git "$(which git)"` to the args I pass `gh-pages` works around this issue.

**Comment by BjornoWalker** [comment]
Thanks for the help, I am having the same issue. Where are you supposed to add --git "$(which git)" exactly?

**Comment by the-simian** [comment]
@BjornoWalker I had problem with @lopopolo 's use of quotes, I used a command like this directly in the command line
`npx gh-pages --dist gh-pages --git $(which git)"

However this wasn't working when I stored it as a command in my package.json

**Comment by BjornoWalker** [comment]
@the-simian Thank you for the response. I'm not sure if it's something that i'm doing on my end, but it still won't work for me even without the quotations. I'm still getting the same `The "file" argument must be of type string. Received type undefined`.

**Comment by the-simian** [comment]
@BjornoWalker try just simply typing `which git` in the command line and see what comes back. I'm also messing with this trying to figure out how to set this as some sort of reusable npm script, which isn't working for me

**Comment by BjornoWalker** [comment]
Thanks a lot, I was finally able to get it to work thanks to your advice! I'm going to keep looking into creating the reusable npm script also.

**Comment by iki** [comment]
@BjornoWalker also, if you don't want to hardcode the git path, you can use `--git git` as git is in `PATH` by default on most systems including Windows, OR you can downgrade to `gh-pages@2.0.1`

**Comment by jonybar9** [comment]
Am facing the same issue.
The work around you guys suggested throws for me:

> Error: spawn $(which git) ENOENT

**Comment by d07RiV** [comment]
Downgrading to 2.0.1 works.

**Comment by the-simian** [comment]
I spent more time on this today and the only thing that worked for me reliably was actually downgrading. My hope is that the non-inclusion of the git switch defaults to 2.0.1 behavior in a future release, but you can override that if you want

**Comment by AffiliateThis** [comment]
I tried updating both the package and lock with versions 2.0.1 and 2.1.0 and I am still getting the same error.   I am a bit stumped here.  This is just a basic react app.   Any suggestions...

> gh-pages@2.0.1 deploy C:\Users\Chris\Desktop\URCoding\GitHub_Work\chrisksportfolio
> gh-pages -d build

The "file" argument must be of type string. Received type undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gh-pages@2.0.1 deploy: `gh-pages -d build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gh-pages@2.0.1 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jonybar9** [comment]
@AffiliateThis 
Guessing you tried it already, but if you haven't:
-Delete node_modules
-Delete package-lock file
-In package.json -> dependencies -> delete gh-pages line

run npm i gh-pages@2.0.1
run npm i
try again.

**Comment by AffiliateThis** [comment]
I actually hadn't tried those steps.  I tried a few other things, but thank-you.  It actually worked.  Something worked....True Happiness in Deployment.

**Comment by kartoos47** [comment]
Thanks..this works.

**Comment by tschaub** [comment]
The gh-pages@2.1.1 release includes a fix for this.
