### ISSUE TITLE
Version 2.1.0 gives error `"file" argument must be a non-empty string`

### ISSUE THREAD

**Issue by dhimmel** [tschaub/gh-pages#310]
Version 2.1.0 produces the following error ([CI logs](https://circleci.com/gh/hetio/frontend-components/33)):

```
"file" argument must be a non-empty string 
```

Downgrading to version 2.0.1 fixed the issue.

Our gh-pages command was:

```shell
gh-pages \
  --dist build \
  --branch build \
  --user 'CircleCI Deploy Job <ci-build@circleci.com>' \
  --message 'Deploy npm package on 2019-08-01
Builds https://github.com/hetio/frontend-components/commit/bf3e385fd25f8884e6301321642474b084143c40
Pushed by https://circleci.com/gh/hetio/frontend-components/33
[skip ci]'
```

The error occurred before a `build` branch existed and after we initialized an empty orphan `build` branch in https://github.com/hetio/frontend-components/commit/b65b4084f47e244688fcf9062176b11cfd7db84f.

Possibly related to https://github.com/tschaub/gh-pages/issues/308. CC @vincerubinetti.

**Comment by doogthemushroom** [comment]
Also experiencing this issue with 2.1. Reverting back to 2.0.1 resolves the issue.

**Comment by NukeManDan** [comment]
Many are:
https://stackoverflow.com/questions/57314473/the-file-argument-must-be-of-type-string-received-type-undefined-on-npm-run-d

**Comment by sassouiabd** [comment]
Also experienced this issue: impossible to deploy react on github pages, i thought the problem was coming from npm... until i saw this thread.

**Comment by shpiglify** [comment]
thats a huge issue !

**Comment by vakeeel** [comment]
When can we expect this to be fixed and released?

**Comment by azangru** [comment]
Doesn’t release 2.1.1 close this issue?

**Comment by nytamin** [comment]
Yes, can confirm that upgrading to 2.1.1 fixes this

**Comment by dhimmel** [comment]
[Here are the changes](https://github.com/tschaub/gh-pages/compare/v2.1.0...v2.1.1) from 2.1.0 to 2.1.1. Would be nice to know what change fixed this issue before closing it. @tschaub mind letting us know and confirming this is fixed?

**Comment by azangru** [comment]
@dhimmel I am sure it was this PR: https://github.com/tschaub/gh-pages/pull/312
