### ISSUE TITLE
Unable to push .nojekyll file to remote gh-pages branch

### ISSUE THREAD

**Issue by rxliuli** [tschaub/gh-pages#315]
![image](https://user-images.githubusercontent.com/24560368/62849718-4cadd600-bd13-11e9-8225-705fbfaaad0e.png)

The .nojekyll file is included in the doc directory, but cannot be pushed to the `gh-pages` branch using the command `gh-pages -d docs`

The directory of the gh-pages branch on the remote GitHub

![image](https://user-images.githubusercontent.com/24560368/62849787-8848a000-bd13-11e9-86b5-df5eb7176962.png)

[GitHub Repo](https://github.com/rxliuli/rx-util)

**Comment by rxliuli** [comment]
Ok, just add the parameter `-t true`. . .

**Comment by k-funk** [comment]
Would be great to have this `-t true` option documented. I don't think many people are using this library for publishing jekyll sites, and would think that a including a `.nojekyll` file at root might even be a default. I wasn't even aware of why my site wasn't serving a directory generated by webpack: `:repoName/_/node_modules/...`

**Comment by mmtolsma** [comment]
Thank you for this. 

My issue was that running `npm run build` was not adding the `.nojekyll` file to my build (what you've named `docs`) folder. I had to do the following in my package.json:
```
"scripts": {
  "build": "vite build && copy .nojekyll build",
  "deploy": "npx gh-pages -d build -t true",
  ...
},
```
