### ISSUE TITLE
Support running a custom script before adding and committing

### ISSUE THREAD

**Issue by Xiphe** [tschaub/gh-pages#331]
I would really like to execute manual cleanup [after new files have been copied but before everything is added](https://github.com/tschaub/gh-pages/blob/master/lib/index.js#L168).

Ideally I could just hook in a function that receives the `git` instance. 

### lib
```js
var ghpages = require('gh-pages');
var getOutdatedBranches = require('./complexCleanupStep');

ghpages.publish(
  'dist',
  {
    async beforeAdd(git) {
        git.rm(await getOutdatedBranches());
    }
  },
  (err) => { /*...*/ }
);
```

### cli
```bash
gh-pages --beforeAdd="./myCustomScript.js"
```

Let me know what you think about this. I'd happily submit a PR.

**Comment by Xiphe** [comment]
@tschaub would you be interested in me providing a PR for this?

**Comment by tschaub** [comment]
Can you describe a bit more about what you are trying to accomplish (maybe with an example)?

**Comment by Xiphe** [comment]
Yeah sure!

I'm building each branch of a project to a subdirectory of `gh-pages` using 
`gh-pages  --add --no-history --dest=${CIRCLE_BRANCH} #--...` in oder to have previews for every WIP.

Now I want to remove folders of deleted branches in order to not have stale previews that nobody cares about anymore.

**Comment by Xiphe** [comment]
Now I really like that `gh-pages` takes care of all the git stuff. And I really don't want to do another clone/update/push just after `gh-pages` is finished doing that. 

Thats why I thought that some kind of hook would work best for me while not adding to much knowledge about the target project to this tool

**Comment by 44px** [comment]
Looks like what I need too for the same use-case (per-branch preview with auto cleanup on merge to master).

**Comment by Xiphe** [comment]
As I said I would love to provide a PR for this (I already had this working via monkey-patching).

@tschaub let me know If you think this would be a good addition.

**Comment by tschaub** [comment]
Sure.

**Comment by airtonix** [comment]
@44px @Xiphe Are either of you able to share how you're using this? I'm specifically interested in 
>  (per-branch preview with auto cleanup on merge to master).

**Comment by Xiphe** [comment]
I used this on a propriatorey project from one of my clients, so I can't point you directly. But I just realise that this is good material for a blogpost. I'll write it down and add a link here.

**Comment by Xiphe** [comment]
Here is an example repo deploying a jekyll build of each branch to /preview/[branchname] and main branch to /
https://github.com/Xiphe/example-ghpage-feature-preview

**Comment by Xiphe** [comment]
Here is the complete walkthrough: https://xiphe.net/blog/automation/preview-every-branch-with-ghpages.html

**Comment by gabrielcsapo** [comment]
@Xiphe this is awesome! Super great addition and awesome article.
