### ISSUE TITLE
Bug: EROFS gh-pages/.cache on yarn-2 - git clone targets .zip file

### ISSUE THREAD

**Issue by Adrian-Grimm** [tschaub/gh-pages#343]
I'm using yarn2 to deploy a gatsby page to github.
"gh-pages": "^2.2.0"
node_js is on version 13

Command `NODE_DEBUG=gh-pages GH_TOKEN=**** yarn deploy` gets following output with an error: 

`
success onPostBuild - 0.174s
info Done building in 15.140969228 sec
GH-PAGES 15514: Cloning https://TEST@github.com/****************.github.io.git into .yarn/cache/gh-pages-npm-2.2.0-7dddbcd165-2.zip/node_modules/gh-pages/.cache/github.com!****************.github.io.git
EROFS: read-only filesystem, mkdir '/node_modules/gh-pages/.cache'
`
He ties to write into the zip file... don't know why...

**Comment by Adrian-Grimm** [comment]
If attach "-base ./ " to the command i gets further progress but now it crashes with: 
`The pattern in the "src" property didn't match any files.`

**Comment by Adrian-Grimm** [comment]
I think the issue is in this method of gh-pages/lib/index.js: 

`
function getCacheDir() {
  return path.relative(process.cwd(), path.resolve(__dirname, '../.cache'));
}`

the cache sould be somewhere else..
maybe options.dest as base for a new package folder?

**Comment by jugglingthebits** [comment]
I have the same issue, and it is blocking my use of gh-pages in a CI pipeline.

@tschaub what would be a proper solution here? A new cache dir param in options, or a different default cache dir in the current dir, as suggested by @Adrian-Grimm ? Would you be interested in a PR?

**Comment by tschaub** [comment]
I think it would be preferable to solve this without adding another option.

**Comment by jugglingthebits** [comment]
@tschaub would it make sense to set the default cache dir to `.gh-pages` (in the project folder)?

**Comment by Adrian-Grimm** [comment]
@jugglingthebits: there is already a pull for my quick fix: https://github.com/tschaub/gh-pages/pull/344 

Until the official version is fixed you can solve it (hacky) like me: https://github.com/cursorbeat/cursorbeat.github.io/commit/838e6df1f07699977de99a8acc6d0e58b9db21d3 ([.yarn/cache/gh-pages-npm-2.2.0-7dddbcd165-2.zip](https://github.com/cursorbeat/cursorbeat.github.io/blob/838e6df1f07699977de99a8acc6d0e58b9db21d3/.yarn/cache/gh-pages-npm-2.2.0-7dddbcd165-2.zip?raw=true)) - commit the whole modified .zip file an modify the .lock file to the new hash: (checksum: 2/85c5bb5506d1eeade54087d4c90211159533a1291854a9318fdd046e4a8a7a8c26327c7667a31af0c812ffa0d58639ca54c879f7ec062bf1d15ccf02f457ddb8)

After a official patch you can revert this commit.

**Comment by tschaub** [comment]
Thanks for the report on this.  It should be fixed in `gh-pages@3.1.0`.  Please open another issue if things still don't work with yarn.
