### ISSUE TITLE
EROFS: read-only filesystem with Yarn 2 

### ISSUE THREAD

**Issue by sumanthratna** [tschaub/gh-pages#358]
when I run `yarn dlx gh-pages -d build`, I get:
```
EROFS: read-only filesystem, mkdir '/node_modules/gh-pages/.cache'
```

- yarn v2.0.0-rc.33
- gh-pages v2.2.0
- macOS 10.15.5 Beta

**EDIT**: this also occurs in a package.json script

**EDIT**: related? https://github.com/tschaub/gh-pages/issues/343

**Comment by tschaub** [comment]
This should be fixed in `gh-pages@3.1.0` (see #362).

**Comment by Adrian-Grimm** [comment]
I only want to confirm that it's fixed - tested in three different projects with yarn2. Thx.

**Comment by tschaub** [comment]
Good news.  Thanks for verifying, @Adrian-Grimm.
