### ISSUE TITLE
Every time I deploy, GitHub Custom domain is overridden 

### ISSUE THREAD

**Issue by MarcinMoskala** [tschaub/gh-pages#370]
I set custom domain, but every time I deploy using this plugin, it is set to some default and I need to set it again. 

Before deploy:
![image](https://user-images.githubusercontent.com/6850787/93190824-1b88ac00-f744-11ea-8c73-990eac676551.png)

Then I deploy with `npm run deploy` and custom domain changes
![image](https://user-images.githubusercontent.com/6850787/93190978-4b37b400-f744-11ea-994b-b3c90e864bdd.png)

**Comment by MarcinMoskala** [comment]
Found CNAME solution

**Comment by neelkarma** [comment]
What's the solution? (I have the same problem)

**Comment by avindra** [comment]
@neelkarma  see #236
