### ISSUE TITLE
Upgrade kramdown to >= 2.3.1, due to security flaw

### ISSUE THREAD

**Issue by KaleabTessera** [tschaub/gh-pages#380]
Please upgrade the kramdown version to `>= 2.3.1` due to a [security flaw](https://github.com/advisories/GHSA-52p9-v744-mwjj).

**Comment by tschaub** [comment]
This project doesn't have a dependency on the [kramdown](https://github.com/gettalong/kramdown) ruby gem.  Let me know if you were thinking of something else.
