### ISSUE TITLE
How to add .well-known directory?

### ISSUE THREAD

**Issue by mikelgmh** [tschaub/gh-pages#381]
I've uploaded a `.well-known` folder to my master branch, but when deploying the project using gh-pages the folder doesn't show up.  This is my config.

```
ghpages.publish('dist', {
  dest: 'myProject-pwa',
  history: false,
  dotfiles: true,
}, function(err) {});
```
As you can see, the dotfiles option is set to true. Is there any way to add manually that folder so it doesn't get ignored?

**Comment by RossJayJones** [comment]
@mikelgmh you can make this work by adding a `_config.yml` file to the public folder with the following context

```
include: [".well-known"]
```
