### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by Virus936** [tschaub/gh-pages#397]
I have this error messages : 
```
> tesla-clone@0.1.0 deploy
> gh-pages -d build

Invalid URL: http:git@github.com:Virus936/tesla-vitrine.git
```

**Comment by viniciuspinatti** [comment]
I worked around this by changing the dev gh-pages dependency of package.json to version 3.2.0
I was having the same problem in version 3.2.1

`
"devDependencies": {
   ...
   "gh-pages": "3.2.0"
}
`

Publish script
`"publish": "gh-pages -d dist/ -d dist/"`

**Comment by lautin0** [comment]
Please check #394 

Upgrading to 3.2.2 should solve the issue

**Comment by tschaub** [comment]
Please update to `gh-pages@3.2.3` (3.2.2 will also solve the issue, 3.2.3 includes a few dependency updates).
