### ISSUE TITLE
error is returned at undefined

### ISSUE THREAD

**Issue by dkebler** [tschaub/gh-pages#40]
Here is my launching code.
```
var done = new Promise( function(resolve,reject){

ghpages.publish(deploySrc, ghconfig[ghconfig.location],function(err,data){
             if(err !== null) {
               console.log('gh publish error:',err);
               return reject(err);}
             resolve(data);
     });

});  // end of promise
```
when run I get at the console `gh publish error: undefined`

it makes the cache file and pushes to repo despite the error although it's returning from the error before the push is complete.

Any way to tell what this error is?? or why it's coming back undefined.   

of note
Just started yesterday.  Initially I wasn't getting any error.
Just upped to node 5.3 yesterday.  Using gh-pages 0.8.0

btw can(does) gh-pages return a promise?  Looks like I saw you using q in the code.

**Comment by dkebler** [comment]
fell back to node 5.1 and gh-pages 0.6 but still having the same issue.

**Comment by tschaub** [comment]
To check for an error, you can just do this:
```js
if (err) {
  // handle the error
}
```

**Comment by dkebler** [comment]
hmmm....guess one shouldn't depend error being returned as "null",  could
be undefined.....   Totally explains why everything worked.

I'm new to js so I suppose there is no standard for this other than cya
with if(err) for all falsy values.

thx.

On Fri, Dec 18, 2015 at 3:00 PM, Tim Schaub <notifications@github.com>
wrote:

> To check for an error, you can just do this:
>
> if (err) {
>   // handle the error
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tschaub/gh-pages/issues/40#issuecomment-165916362>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David
