### ISSUE TITLE
Remove dependence for `collections`

### ISSUE THREAD

**Issue by morlay** [tschaub/gh-pages#42]
This one will broken other libs 
because of https://github.com/montagejs/collections/issues/139

```
+-- gh-pages@0.8.0
| +-- async@1.5.0
| +-- glob@6.0.3
| +-- graceful-fs@4.1.2
| +-- q@1.4.1
| +-- q-io@1.13.2
| | +-- collections@0.2.2
| | | `-- weak-map@1.0.0
| | +-- mimeparse@0.1.4
| | +-- qs@1.2.2
| | `-- url2@0.0.0
| `-- wrench@1.5.8
```

btw, global shim is dangerous

**Comment by markdalgleish** [comment]
Would you mind issuing a PR for this?

**Comment by morlay** [comment]
sure, i will try fix it this weekend.

seems `q-io` only in https://github.com/tschaub/gh-pages/blob/master/lib/git.js

**Comment by tschaub** [comment]
Q and q-io are gone with #166.
