### ISSUE TITLE
after running npm run deploy I am getting below error

### ISSUE THREAD

**Issue by akshaymalik75** [tschaub/gh-pages#442]
Cloning into 'D:\Practice\React\Restaurant App\restaurantapp\node_modules.cache\gh-pages\https!akshaymalik75.github.io!React_forms'...
fatal: repository 'https://akshaymalik75.github.io/React_forms/' not found

I am getting this error even though I have changed the repo name please help.
![git issue](https://user-images.githubusercontent.com/25265773/187034916-d2de8b98-193b-4fa1-8fdb-548ecd9fc138.PNG)

**Comment by akshaymalik75** [comment]
resolved

**Comment by sharadbhat** [comment]
@akshaymalik75 please help others out by explaining how you resolved it. Thanks!
