### ISSUE TITLE
gh-pages overwrites the CNAME

### ISSUE THREAD

**Issue by njmulsqb** [tschaub/gh-pages#503]
Hi,

Whenever I publish the site, it overwrites the CNAME from the gh-pages branch, also it is not taking into account CNAME from the branch I am deploying, so with each deploy I have to manually add the CNAME which is time taking

**Comment by 70nyIT** [comment]
same issue here - need to manually re-deploy CNAME file

**Comment by jamescourson** [comment]
This is the intended functionality - the output of your build step is copied into your build directory, which will overwrite any file inside of it (not just CNAME). I encountered the same issue and found [this section of the readme](https://github.com/tschaub/gh-pages#deploying-to-github-pages-with-custom-domain) useful.

I ended up adding an extra step to my predeploy script in `package.json`, writing the file after the build step and before deployment:
`"predeploy": "yarn run build && echo your.website > CNAME"`
