### ISSUE TITLE
Cache per repo?

### ISSUE THREAD

**Issue by KyleAMathews** [tschaub/gh-pages#58]
With the globally installed `gh-pages` executable, trying to deploy multiple repos causes conflicts in the `.cache` directory. It'd be handy of repos were cloned to their own directory _within_ the `.cache` directory to avoid conflicts.

**Comment by mesupp** [comment]
sorry man i understand  i will make an own partition for it didnt expect that mutch pull.. moment i noticed i turned the services of and shut down.... again sorry and tnx for the advice!

**Comment by cliffano** [comment]
To help those googling the error message to arrive at this issue, here's the error snippet:

Cloning <curr-repo-url> into <node-base>/lib/node_modules/gh-pages/.cache
Remote url mismatch.  Got "<last-repo-url>" but expected "<curr-repo-url>" in <node-base>/lib/node_modules/gh-pages/.cache.  If you have changed your "repo" option, try running the "clean" task first.
