### ISSUE TITLE
How to handle archival builds with gh-pages?

### ISSUE THREAD

**Issue by bebraw** [tschaub/gh-pages#93]
I deploy the documentation sites of many of my projects through gh-pages. A while ago I realized that instead of nuking the whole site each time I publish, it would be nice to archive the old one below the previous version in the directory tree.

Is there some nice way to pull this off with gh-pages?

**Comment by tschaub** [comment]
You can use the [`add`](https://github.com/tschaub/gh-pages#optionsadd) option for this.  For example, if you wanted to leave old versions around, could do this by building new artifacts in a directory named like the version.  For example, `build/v1.2.3` would be generated when building `v1.2.3`.  Then you can do this:

    ghpages.publish('build', {add: true}, callback);

**Comment by bebraw** [comment]
Perfect! Thanks a lot.
